// <auto-generated />
using System;
using FinancesBackend.Efc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancesBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinancesBackend.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 5,
                            DateTime = new DateTime(2022, 9, 9, 10, 47, 42, 160, DateTimeKind.Local).AddTicks(8051),
                            Name = "Office restock",
                            Value = 245.5
                        },
                        new
                        {
                            Id = 2,
                            Category = 4,
                            DateTime = new DateTime(2022, 11, 27, 10, 47, 42, 160, DateTimeKind.Local).AddTicks(8090),
                            Name = "Business trip",
                            Value = 320.75
                        },
                        new
                        {
                            Id = 3,
                            Category = 2,
                            DateTime = new DateTime(2022, 12, 8, 10, 47, 42, 160, DateTimeKind.Local).AddTicks(8093),
                            Name = "Business dinner",
                            Value = 100.0
                        },
                        new
                        {
                            Id = 4,
                            Category = 3,
                            DateTime = new DateTime(2022, 12, 9, 10, 47, 42, 160, DateTimeKind.Local).AddTicks(8095),
                            Name = "PC restock",
                            Value = 7500.75
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
